### PR TITLE
Extension shouldn't be enabled in pb mode as it's currently not worki…

### LINKED ISSUE #756: An infinite number of each hidden container is shown when choosing "Show this container" option in Private Browsing mode
**[Notes]:**
- On the latest Firefox Release 55.0.2 the issue is not reproducible. However, when choosing the "Show this container" option, two of the same container tabs are opened in the non-private window.

**[Affected versions]:**
- Firefox unbranded build (56.0b2-20170810113054)
- Nightly build (57.0a1-20170822171841)

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Containers add-on version (3.1.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open two or more tabs of the same container type.
3. Click on the "Containers" toolbar button.
4. Choose the "Hide this container" option for the current container type.
5. Open a New Private Window (CTRL+Shift+P).
6. Click on the "Containers" toolbar button.
7. Choose the "Show this container" option for the hidden container tabs.
8. Switch to the non-private Firefox window and observe the browser behaviour.

**[Expected result]:**
- Only one instance of each hidden container tab is shown in the non-private window.

**[Actual result]:**
- An infinite number of each hidden container tab is shown in the non-private window.

**[Additional Notes]:**
- Attached a screen recording of the issue:
containers_issue

### PR DESCRIPTION
**Pull request by jonathanKingston**
…ng in many places. Fixes #756

### CODE REVIEW

File: webextension/js/background/messageHandler.js [hunk 1]
```diff
@@ -161,6 +148,24 @@ const messageHandler = {
...
+    assignManager.removeContextMenu();
+    const currentWindow = await browser.windows.getCurrent();
+    // browserAction loses background color in new windows ...
+    // https://bugzil.la/1314674
+    // https://github.com/mozilla/testpilot-containers/issues/608
+    // ... so re-call displayBrowserActionBadge on window changes
+    badge.displayBrowserActionBadge(currentWindow.incognito);
+    browser.tabs.query({active: true, windowId}).then((tabs) => {
+      if (tabs && tabs[0]) {
+        tabPageCounter.initTabCounter(tabs[0]);
```
Comment (groovecoder) [inline webextension/js/background/messageHandler.js]: We can remove all this `tabPageCounter` stuff ... I'll file a follow-up issue.

File: webextension/js/popup.js [hunk 2]
```diff
@@ -451,7 +451,7 @@ Logic.registerPanel(P_CONTAINERS_LIST, {
   panelSelector: "#container-panel",
 
   // This method is called when the object is registered.
-  initialize() {
+  async initialize() {
```
Comment (groovecoder) [inline webextension/js/popup.js]: Looks like an un-related fix, but it looks okay.

File: webextension/js/background/messageHandler.js (hunk 1 above)
Comment (groovecoder) [inline webextension/js/background/messageHandler.js]: Filed https://github.com/mozilla/testpilot-containers/issues/759
