### PR TITLE
Fixing about: scheme assignment. Fixes #413

### LINKED ISSUE #413: Some about: protocol urls can assign to a container
It doesn't actually assign etc however it's confusing
selection_555

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

File: webextension/background.js [hunk 1]
```diff
@@ -160,7 +160,8 @@ const assignManager = {
   isTabPermittedAssign(tab) {
     // Ensure we are not an important about url
     // Ensure we are not in incognito mode
-    if (this.CLOSEABLE_WINDOWS.has(tab.url)
+    const url = URL(tab.url);
```
Comment (groovecoder) [inline webextension/background.js]: `TypeError: Constructor URL requires 'new'`
