### PR TITLE
Fix different display in content warning notice. Fixes #630

### LINKED ISSUE #630: "Always Open in This Container" notification is displayed differently for some websites
[Affected versions]:
- Firefox 54.0 and up
- Containers Experiment Build: 2.3.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Containers Experiment is installed on a new browser profile.

[Steps to reproduce]:
1. Start Firefox with the profile from prerequisites.
2. Open a new tab in a container (e.g. "Personal") and navigate to www.twitch.tv
3. Right click on the page's content.
4. Click on "Always Open in This Container" and observe the notification under the URL bar.
5. Follow steps 2-4 using the following websites:
- https://giphy.com
- https://soundcloud.com
- https://vimeo.com
- https://www.reddit.com
- https://www.britannica.com

[Expected results]:
- The text from the notification has the same font size, format and alignment for all websites.

[Actual results]:
- The text from the notification has different font size, format and alignment depending on the website.

[Notes]:
- Please see the following screenshot of the issue:

fgaeg

### PR DESCRIPTION
**Pull request by jonathanKingston**
This likely won't solve all layout issues that we find. Loading it earlier prevents it from not being shown at all on page load.

Looks like we just need to override every property that the page might get, which is a long list. I fixed all the examples to all look the same.

We can review better post release.

### CODE REVIEW

**Comment by groovecoder** [comment]
This looks consistent now, but the text isn't center|middle-aligned with the containers icon in the notification?

image

**Comment by jonathanKingston** [comment]
It never was... but I will make it :P give me a few mins

File: webextension/js/content-script.js [hunk 1]
```diff
@@ -43,9 +43,9 @@ async function addMessage(message) {
   await delayAnimation(100);
   await doAnimation(divElement, "transform", "translateY(0)");
   await delayAnimation(2000);
-  await doAnimation(divElement, "transform", "translateY(-100%)");
+  //await doAnimation(divElement, "transform", "translateY(-100%)");
```
Comment (groovecoder) [inline webextension/js/content-script.js]: Why are we keeping these lines instead of just removing them?

File: webextension/js/content-script.js [hunk 2]
```diff
@@ -43,9 +43,9 @@ async function addMessage(message) {
...
 
-  divElement.remove();
+  //divElement.remove();
```
Comment (groovecoder) [inline webextension/js/content-script.js]: Why are we keeping these lines instead of just removing them?

File: webextension/js/content-script.js (hunk 1 above)
Comment (jonathanKingston) [inline webextension/js/content-script.js]: Crap sorry.
